[package]
name = "test_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
kmd_client.workspace = true
algod_client.workspace = true
anyhow = "1.0.100"
tokio = "1.49.0"

[dev-dependencies]
tokio = { version = "1.49.0", features = ["macros"] }

