rust:
  directory: .
  manifestPath: crates/mithras-crypto-ffi/Cargo.toml
web:
  ts: pkg
  wasmCrateName: mithras-crypto-wasm
  workspace: false
  rustflags: ['--cfg', 'getrandom_backend="wasm_js"']
bindings:
  ts: pkg
