[package]
name = "mithras-crypto-ffi"
version = "0.1.0"
edition = "2024"

[dependencies]
ed25519-dalek = "2.2.0"
mithras-crypto = { version = "0.1.0", path = "../mithras-crypto" }
uniffi.workspace = true
x25519-dalek = "2.0.1"
